# Generated by Django 3.1.5 on 2021-08-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_yazilarmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yazilarmodel',
            name='icerik',
        ),
    ]
