# Generated by Django 3.1.5 on 2021-08-25 07:38

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_yazilarmodel_icerik'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazilarmodel',
            name='icerik',
            field=ckeditor.fields.RichTextField(),
            preserve_default=False,
        ),
    ]
